### PR TITLE
Custom parent breadcrumbs

### PR DESCRIPTION
**Pull request by sash**
@ampeco we had to create dependant resources that are always parented by another resource, thus creating a larger breadcrumb tree and even showing the full listing of the dependent resource. 

This is why I created this fork and implemented the functionality

In order to use it do 
```php
class PaymentMethod extends Resource{
   //...
    protected function breadcrumbParents()
    {
        return [
            '/resources/users'                   => 'Users',
            '/resources/users/' . $this->user_id => $this->user->names,
        ];
    }

}
```

### CODE REVIEW

**Comment by chris-ware** [comment]
I'd prefer to not have to manually enter the URLs if at all possible. This leaves quite a lot of room for user error.

**Comment by sash** [comment]
I agree. That is just our use case and I didn’t have more time to spend on it. Perhaps a better option would be to declare the relations in some way and generate the labels and urls from those. I don’t have a good idea on how to do that so it works even with second level relations - User.Posts.Comment for example

**Comment by chris-ware** [comment]
There is a way to do this, which I think would be much cleaner, but I need some time to investigate. The way I'd possibly achieve this is more along the lines of having Nova itself generate the URL via the resource, but the question would be what input does it take in order to make it clean and easy to use.

**Comment by addgod** [comment]
This would be an awesome feature. Since else this package cannot show nested breadcrums and kinda make it much more useable. I would implement like the redirectAfterCreate. so public static setParentResource(NovaRequest $request, $resource). Thas would make it clean and easy to use.

**Comment by chris-ware** [comment]
I'm probably not going to implement this the way that the PR has suggested or the way that you have suggested either. I haven't had any time to spend on V2 of this package, but with that, it utilises the URL parameters of Nova to determine if the item is a child relationship or not. Allowing you to manually set the parent of the Resource makes things miles harder from a URL handling perspective as at that point and as of yet, I've not seen got a solution that is clean and consistent. Maybe once V2 is released, someone can PR into that, but for now, it isn't happening.

**Comment by chris-ware** [comment]
As per my earlier comment, I'm not going to be accepting this PR, due to the release of Version 2 drastically changing how this package works. I'd happily accept a PR using the new version, as long as the behaviour is opt-in and controllable, not opt-out.

**Pull request closed without merging**
